### PR TITLE
Add build job with GitHub Actions

### PR DESCRIPTION
**Pull request by mueller-ma**
I saw you're using Gitlab CI, but only on master, not on PRs. This PR adds a build job on GitHub Actions.

### CODE REVIEW

**Comment by csicar** [comment]
Yeah.. I got annoyed by that as well. It's fixed now :)

**Comment by csicar** [comment]
I actually prefer gitlab ci for 2 reasons:
- It automatically syncs with Gitlab, meaning developers can use the platform they prefer
- I can run my own CI Runner

TBH I haven't used Github Actions much, so if I'm missing something or GitHub Actions also offers running your own runners, I'd be happy to give it a try

**Comment by mueller-ma** [comment]
> GitHub Actions also offers running your own runners.

You can, but isn't a runner provided by GitHub or Gitlab better? If using your own runner, anyone could open a PR and run untrusted code on your node.

**Comment by csicar** [comment]
Yes, that's right. Luckily the runners are adequately locked down, so that ci jobs should never escape the sandbox. It would still be possible to run a crypto miner, but that should be easy enough to stop

**Comment by mueller-ma** [comment]
Ok, so feel free to close this PR.

**Pull request closed without merging**
